---
- name: OBS studio setup.
  debug:
    msg:
      - '---------------------------------------------------------------------'
      - 'Setting up OBS studio ...'
      - '---------------------------------------------------------------------'

- name: Gather facts.
  setup:

- name: Install obs-studio.
  debug:
    msg:
      - '---------------------------------------------------------------------'
      - 'Installing obs-studio ...'
      - '---------------------------------------------------------------------'

- name: On Ubuntu add obs-studio ppa.
  apt_repository:
    repo: ppa:obsproject/obs-studio
  become: true
  when:
    - not ansible_check_mode
    - ansible_distribution == 'Ubuntu'

- name: On Ubuntu update APT cache.
  apt:
    update_cache: true
  register: result
  retries: 2
  until: result is success
  become: true
  changed_when: false
  when:
    - not ansible_check_mode
    - ansible_distribution == 'Ubuntu'

- name: Install obs-studio
  apt:
    name: obs-studio
  register: result
  retries: 2
  until: result is success
  become: true
  when: not ansible_check_mode